name: "Firefox via noVNC"
version: "1.0"
slug: "firefox_novnc"
description: "Navigateur Firefox accessible via VNC depuis un navigateur web"
startup: services
boot: auto
hassio_api: false
homeassistant_api: false
host_network: false
privileged: []
ports:
  5800/tcp: 5800
image: "jlesage/firefox"
